use [Library]
go

insert into Countries (Name) values ('Malaysia');
insert into Countries (Name) values ('Albania');
insert into Countries (Name) values ('Colombia');
insert into Countries (Name) values ('Kuwait');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Kazakhstan');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Greece');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('Ukraine');
insert into Countries (Name) values ('USA');


insert into Authors (Name, Surname, CountrieId) values ('Arte', 'Sacaze', 12);
insert into Authors (Name, Surname, CountrieId) values ('Dareen', 'Raffeorty', 5);
insert into Authors (Name, Surname, CountrieId) values ('Alfreda', 'McGawn', 10);
insert into Authors (Name, Surname, CountrieId) values ('Lilith', 'Arbuckel', 4);
insert into Authors (Name, Surname, CountrieId) values ('Leola', 'Peggrem', 1);
insert into Authors (Name, Surname, CountrieId) values ('Dino', 'Kiendl', 9);
insert into Authors (Name, Surname, CountrieId) values ('Rebekah', 'Di Filippo', 3);
insert into Authors (Name, Surname, CountrieId) values ('Shepherd', 'Vannah', 11);
insert into Authors (Name, Surname, CountrieId) values ('Rodolfo', 'Blinerman', 4);
insert into Authors (Name, Surname, CountrieId) values ('Florenza', 'Espada', 2);
insert into Authors (Name, Surname, CountrieId) values ('Reggis', 'Jago', 9);
insert into Authors (Name, Surname, CountrieId) values ('Solly', 'Hoodless', 9);
insert into Authors (Name, Surname, CountrieId) values ('Von', 'Grumell', 12);
insert into Authors (Name, Surname, CountrieId) values ('Daria', 'Eliff', 4);
insert into Authors (Name, Surname, CountrieId) values ('Wilona', 'Dunsmore', 7);
insert into Authors (Name, Surname, CountrieId) values ('Pat', 'Reeman', 11);
insert into Authors (Name, Surname, CountrieId) values ('Ralph', 'Grouvel', 7);
insert into Authors (Name, Surname, CountrieId) values ('Jerrilyn', 'Sommerland', 10);
insert into Authors (Name, Surname, CountrieId) values ('Ivonne', 'Harome', 7);
insert into Authors (Name, Surname, CountrieId) values ('Bradley', 'Sloegrave', 2);


insert into Books (Name, PageCount, AuthorId) values ('Schaerer''s Psorotichia Lichen', 156, 20);
insert into Books (Name, PageCount, AuthorId) values ('Wright''s False Threadleaf', 178, 13);
insert into Books (Name, PageCount, AuthorId) values ('Sand Palafox', 100, 16);
insert into Books (Name, PageCount, AuthorId) values ('Fitchia', 332, 1);
insert into Books (Name, PageCount, AuthorId) values ('Melaspilea Lichen', 276, 3);
insert into Books (Name, PageCount, AuthorId) values ('Carite Babyboot Orchid', 367, 11);
insert into Books (Name, PageCount, AuthorId) values ('New Mexico Milkvetch', 89, 17);
insert into Books (Name, PageCount, AuthorId) values ('Puerto Rico Yellowcress', 107, 19);
insert into Books (Name, PageCount, AuthorId) values ('Pitcher Sage', 65, 17);
insert into Books (Name, PageCount, AuthorId) values ('Quillwort', 504, 3);
insert into Books (Name, PageCount, AuthorId) values ('Fineleaf Waterdropwort', 314, 20);
insert into Books (Name, PageCount, AuthorId) values ('Common Goldenthistle', 172, 11);
insert into Books (Name, PageCount, AuthorId) values ('Rough Blackfoot', 116, 8);
insert into Books (Name, PageCount, AuthorId) values ('Pore Lichen', 155, 7);
insert into Books (Name, PageCount, AuthorId) values ('Capetown Pea', 567, 11);
insert into Books (Name, PageCount, AuthorId) values ('Passionflower', 285, 20);
insert into Books (Name, PageCount, AuthorId) values ('Hard Treefern', 594, 9);
insert into Books (Name, PageCount, AuthorId) values ('Wreath Lichen', 564, 2);
insert into Books (Name, PageCount, AuthorId) values ('Fiveleaf Orchid', 94, 13);
insert into Books (Name, PageCount, AuthorId) values ('Rim Lichen', 284, 10);
insert into Books (Name, PageCount, AuthorId) values ('Haitian Catalpa', 468, 15);
insert into Books (Name, PageCount, AuthorId) values ('Crocynia Lichen', 246, 16);
insert into Books (Name, PageCount, AuthorId) values ('Queen Of The Night', 196, 10);
insert into Books (Name, PageCount, AuthorId) values ('Garbancillo', 284, 4);
insert into Books (Name, PageCount, AuthorId) values ('Trampweed', 250, 15);
insert into Books (Name, PageCount, AuthorId) values ('Parmotrema Lichen', 531, 17);
insert into Books (Name, PageCount, AuthorId) values ('Oersted''s Atrichum Moss', 128, 12);
insert into Books (Name, PageCount, AuthorId) values ('Watermelon', 121, 9);
insert into Books (Name, PageCount, AuthorId) values ('Everniastrum Lichen', 351, 1);
insert into Books (Name, PageCount, AuthorId) values ('Lecidea Lichen', 95, 6);
insert into Books (Name, PageCount, AuthorId) values ('Northern Eyebright', 496, 20);
insert into Books (Name, PageCount, AuthorId) values ('Aceitunilla', 192, 20);
insert into Books (Name, PageCount, AuthorId) values ('Louisiana Broomrape', 322, 18);
insert into Books (Name, PageCount, AuthorId) values ('Pimientillo', 519, 11);
insert into Books (Name, PageCount, AuthorId) values ('Woodland Dewberry', 310, 11);
insert into Books (Name, PageCount, AuthorId) values ('Steptoe Valley Beardtongue', 285, 19);
insert into Books (Name, PageCount, AuthorId) values ('Santa Monica Mountains Dudleya', 577, 15);
insert into Books (Name, PageCount, AuthorId) values ('Beckwith''s Clover', 171, 1);
insert into Books (Name, PageCount, AuthorId) values ('Rannoch-rush', 133, 12);
insert into Books (Name, PageCount, AuthorId) values ('Roughpod Bladderpod', 188, 7);
insert into Books (Name, PageCount, AuthorId) values ('Santa Catalina Figwort', 160, 7);
insert into Books (Name, PageCount, AuthorId) values ('Peltula Lichen', 253, 19);
insert into Books (Name, PageCount, AuthorId) values ('Armand Pine', 530, 7);
insert into Books (Name, PageCount, AuthorId) values ('Nadvornikia', 523, 20);
insert into Books (Name, PageCount, AuthorId) values ('Dot Lichen', 471, 6);
insert into Books (Name, PageCount, AuthorId) values ('Saltmarsh Umbrella-sedge', 243, 19);
insert into Books (Name, PageCount, AuthorId) values ('Norway Sedge', 76, 14);
insert into Books (Name, PageCount, AuthorId) values ('Giant Vetch', 178, 1);
insert into Books (Name, PageCount, AuthorId) values ('Brouard''s Rinodina Lichen', 281, 12);
insert into Books (Name, PageCount, AuthorId) values ('Maquei', 228, 13);